# Generated by Django 3.0.8 on 2020-09-26 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_title', models.CharField(max_length=200)),
                ('r_rent', models.CharField(max_length=100)),
                ('r_desc', models.TextField(max_length=300)),
                ('r_image', models.ImageField(upload_to='image')),
                ('r_slug', models.SlugField()),
                ('r_status', models.CharField(choices=[('0', 'Pending'), ('1', 'Active')], default='1', max_length=20)),
                ('r_doc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('rt_id', models.AutoField(primary_key=True, serialize=False)),
                ('rt_title', models.CharField(max_length=200)),
                ('rt_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100, unique=True)),
                ('s_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomRenter',
            fields=[
                ('rr_id', models.AutoField(primary_key=True, serialize=False)),
                ('rr_contact', models.CharField(max_length=10)),
                ('rr_image', models.ImageField(upload_to='profile')),
                ('rr_street', models.TextField(max_length=300)),
                ('rr_id_proof', models.ImageField(upload_to='profile/proof')),
                ('rr_proof_no', models.CharField(max_length=4)),
                ('rr_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.City')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomOwner',
            fields=[
                ('ro_id', models.AutoField(primary_key=True, serialize=False)),
                ('ro_image', models.ImageField(upload_to='profile')),
                ('ro_contact', models.CharField(max_length=10)),
                ('ro_street', models.TextField(max_length=300)),
                ('ro_id_proof', models.ImageField(upload_to='profile/proof')),
                ('ro_house', models.CharField(max_length=100)),
                ('ro_house_image', models.ImageField(upload_to='image')),
                ('ro_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.City')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAllot',
            fields=[
                ('ra_id', models.AutoField(primary_key=True, serialize=False)),
                ('ra_doc', models.DateTimeField(auto_now_add=True)),
                ('ra_status', models.CharField(choices=[('0', 'Pending'), ('1', 'Active')], default='1', max_length=20)),
                ('ra_slug', models.SlugField()),
                ('ra_room_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.Room')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='renter', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='r_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.RoomType'),
        ),
        migrations.AddField(
            model_name='room',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentPaid',
            fields=[
                ('pp_id', models.AutoField(primary_key=True, serialize=False)),
                ('pp_txn', models.CharField(max_length=100)),
                ('pp_amount', models.CharField(max_length=100)),
                ('pp_month', models.CharField(max_length=100)),
                ('pp_doc', models.DateTimeField(auto_now_add=True)),
                ('pp_slug', models.SlugField()),
                ('pp_room_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.Room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGenerate',
            fields=[
                ('pg_id', models.AutoField(primary_key=True, serialize=False)),
                ('pg_txn', models.CharField(max_length=100)),
                ('pg_amount', models.CharField(max_length=100)),
                ('pg_month', models.CharField(max_length=100)),
                ('pg_doc', models.DateTimeField(auto_now_add=True)),
                ('pg_slug', models.SlugField()),
                ('pg_room_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.Room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='s_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.State'),
        ),
    ]
