# Generated by Django 3.2.9 on 2022-05-13 18:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnerHouse',
            fields=[
                ('ho_id', models.AutoField(primary_key=True, serialize=False)),
                ('ho_contact', models.CharField(max_length=10, unique=True)),
                ('ho_street', models.CharField(max_length=200)),
                ('house_name', models.CharField(max_length=100)),
                ('house_image', models.ImageField(upload_to='image')),
                ('slug', models.SlugField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.city')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_title', models.CharField(max_length=100)),
                ('r_rent', models.IntegerField()),
                ('r_desc', models.CharField(max_length=200)),
                ('r_image', models.ImageField(upload_to='image')),
                ('slug', models.SlugField()),
                ('r_status', models.CharField(choices=[('0', 'Pending'), ('1', 'Active')], default='1', max_length=20)),
                ('r_doc', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 13, 18, 23, 56, 350903))),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.ownerhouse')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('rt_id', models.AutoField(primary_key=True, serialize=False)),
                ('rt_title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomRenter',
            fields=[
                ('rr_id', models.AutoField(primary_key=True, serialize=False)),
                ('rr_contact', models.CharField(max_length=10, unique=True)),
                ('rr_image', models.ImageField(upload_to='profile')),
                ('rr_street', models.CharField(max_length=200)),
                ('rr_id_proof', models.ImageField(upload_to='profile/proof')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.state')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomQuery',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=100)),
                ('m_contact', models.CharField(max_length=10)),
                ('m_message', models.CharField(max_length=200)),
                ('m_doc', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 13, 18, 23, 56, 351795))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomOwner',
            fields=[
                ('ro_id', models.AutoField(primary_key=True, serialize=False)),
                ('ro_image', models.ImageField(upload_to='profile')),
                ('ro_contact', models.CharField(max_length=10, unique=True)),
                ('ro_street', models.CharField(max_length=200)),
                ('ro_id_proof', models.ImageField(upload_to='profile/proof')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.state')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAllot',
            fields=[
                ('ra_id', models.AutoField(primary_key=True, serialize=False)),
                ('ra_doc', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 13, 18, 23, 56, 351527))),
                ('ra_status', models.CharField(choices=[('0', 'Request'), ('1', 'Active'), ('2', 'Pending')], default='1', max_length=20)),
                ('slug', models.SlugField()),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.ownerhouse')),
                ('ra_room_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.room')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='renter', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='r_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.roomtype'),
        ),
        migrations.AddField(
            model_name='room',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentPaid',
            fields=[
                ('pp_id', models.AutoField(primary_key=True, serialize=False)),
                ('pp_txn', models.CharField(max_length=100)),
                ('pp_amount', models.IntegerField()),
                ('pp_doc', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 13, 18, 23, 56, 352271))),
                ('slug', models.SlugField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_id', to=settings.AUTH_USER_MODEL)),
                ('pp_allot_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.roomallot')),
                ('renter_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='renter_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGenerate',
            fields=[
                ('pg_id', models.AutoField(primary_key=True, serialize=False)),
                ('pg_txn', models.CharField(max_length=100)),
                ('pg_amount', models.IntegerField()),
                ('pg_month', models.DateTimeField()),
                ('pg_doc', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 13, 18, 23, 56, 352001))),
                ('slug', models.SlugField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_owner', to=settings.AUTH_USER_MODEL)),
                ('pg_allot_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.roomallot')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_renter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ownerhouse',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.state'),
        ),
        migrations.AddField(
            model_name='ownerhouse',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.state'),
        ),
    ]
