# Generated by Django 3.0.8 on 2020-09-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallot',
            name='ra_status',
            field=models.CharField(choices=[('0', 'Request'), ('1', 'Active'), ('2', 'Pending')], default='1', max_length=20),
        ),
    ]
