# Generated by Django 3.1.1 on 2020-10-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0002_auto_20200929_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomrenter',
            name='rr_proof_no',
        ),
        migrations.AddField(
            model_name='roomowner',
            name='ro_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datawork.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomrenter',
            name='rr_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.state'),
            preserve_default=False,
        ),
    ]
