# Generated by Django 3.1.1 on 2020-10-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0003_auto_20201002_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='c_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='s_name',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='paymentgenerate',
            old_name='pg_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='paymentpaid',
            old_name='pp_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='r_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='roomallot',
            old_name='ra_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='roomowner',
            old_name='ro_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='roomowner',
            old_name='ro_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='roomrenter',
            old_name='rr_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='roomrenter',
            old_name='rr_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='rt_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='s_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='s_slug',
            new_name='slug',
        ),
    ]
