# Generated by Django 3.1.1 on 2020-10-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0004_auto_20201002_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomowner',
            name='ro_contact',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='roomrenter',
            name='rr_contact',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
