# Generated by Django 3.1.1 on 2020-10-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0005_auto_20201003_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='r_desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roomowner',
            name='ro_street',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='roomrenter',
            name='rr_street',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='rt_title',
            field=models.CharField(max_length=100),
        ),
    ]
