# Generated by Django 3.1.1 on 2020-10-09 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0007_roomquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomquery',
            name='m_doc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
