# Generated by Django 3.1.1 on 2020-10-10 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0008_roomquery_m_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgenerate',
            name='pg_allot_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.roomallot'),
            preserve_default=False,
        ),
    ]
