# Generated by Django 3.1.1 on 2020-10-12 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0009_paymentgenerate_pg_allot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgenerate',
            name='pg_room_id',
        ),
    ]
