# Generated by Django 3.1.1 on 2020-10-13 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0013_auto_20201012_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgenerate',
            name='pg_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentgenerate',
            name='pg_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 1, 46, 31, 27789)),
        ),
        migrations.AlterField(
            model_name='paymentpaid',
            name='pp_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentpaid',
            name='pp_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 1, 46, 31, 28787)),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 1, 46, 31, 20817)),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_rent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomallot',
            name='ra_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 1, 46, 31, 24797)),
        ),
        migrations.AlterField(
            model_name='roomquery',
            name='m_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 1, 46, 31, 25795)),
        ),
    ]
