# Generated by Django 3.1.1 on 2020-10-13 20:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0014_auto_20201014_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentpaid',
            name='pp_room_id',
        ),
        migrations.AddField(
            model_name='paymentpaid',
            name='pp_allot_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.roomallot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentgenerate',
            name='pg_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 2, 2, 24, 126833)),
        ),
        migrations.AlterField(
            model_name='paymentpaid',
            name='pp_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 2, 2, 24, 128828)),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 2, 2, 24, 120849)),
        ),
        migrations.AlterField(
            model_name='roomallot',
            name='ra_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 2, 2, 24, 124839)),
        ),
        migrations.AlterField(
            model_name='roomquery',
            name='m_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 2, 2, 24, 125837)),
        ),
    ]
