# Generated by Django 3.1.1 on 2020-10-14 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0016_auto_20201014_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgenerate',
            name='pg_doc',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymentpaid',
            name='pp_doc',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 23, 35, 30, 709287)),
        ),
        migrations.AlterField(
            model_name='roomallot',
            name='ra_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 23, 35, 30, 711282)),
        ),
        migrations.AlterField(
            model_name='roomquery',
            name='m_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 23, 35, 30, 714278)),
        ),
    ]
