# Generated by Django 3.1.1 on 2020-10-14 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0018_auto_20201014_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgenerate',
            name='pg_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 23, 40, 32, 946227)),
        ),
        migrations.AlterField(
            model_name='paymentpaid',
            name='pp_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 23, 40, 32, 947224)),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 23, 40, 32, 940241)),
        ),
        migrations.AlterField(
            model_name='roomallot',
            name='ra_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 23, 40, 32, 944231)),
        ),
        migrations.AlterField(
            model_name='roomquery',
            name='m_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 23, 40, 32, 945227)),
        ),
    ]
