# Generated by Django 3.1.1 on 2020-10-14 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0019_auto_20201014_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgenerate',
            name='pg_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 23, 51, 32, 775736)),
        ),
        migrations.AlterField(
            model_name='paymentgenerate',
            name='pg_month',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymentpaid',
            name='pp_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 23, 51, 32, 776734)),
        ),
        migrations.AlterField(
            model_name='paymentpaid',
            name='pp_month',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 23, 51, 32, 769750)),
        ),
        migrations.AlterField(
            model_name='roomallot',
            name='ra_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 23, 51, 32, 772744)),
        ),
        migrations.AlterField(
            model_name='roomquery',
            name='m_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 14, 23, 51, 32, 774738)),
        ),
    ]
