# Generated by Django 3.1.1 on 2020-10-19 20:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datawork', '0021_auto_20201018_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentpaid',
            name='user_id',
        ),
        migrations.AddField(
            model_name='paymentpaid',
            name='owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_id', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentpaid',
            name='renter_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='renter_id', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentgenerate',
            name='pg_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 20, 2, 20, 20, 355654)),
        ),
        migrations.AlterField(
            model_name='paymentpaid',
            name='pp_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 20, 2, 20, 20, 355654)),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 20, 2, 20, 20, 351641)),
        ),
        migrations.AlterField(
            model_name='roomallot',
            name='ra_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 20, 2, 20, 20, 355654)),
        ),
        migrations.AlterField(
            model_name='roomquery',
            name='m_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 20, 2, 20, 20, 355654)),
        ),
    ]
