# Generated by Django 3.1.1 on 2020-11-04 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0023_auto_20201022_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgenerate',
            name='pg_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 5, 0, 20, 3, 973055)),
        ),
        migrations.AlterField(
            model_name='paymentpaid',
            name='pp_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 5, 0, 20, 3, 974053)),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 5, 0, 20, 3, 967071)),
        ),
        migrations.AlterField(
            model_name='roomallot',
            name='ra_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 5, 0, 20, 3, 970063)),
        ),
        migrations.AlterField(
            model_name='roomowner',
            name='ro_street',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='roomquery',
            name='m_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 5, 0, 20, 3, 971060)),
        ),
        migrations.AlterField(
            model_name='roomrenter',
            name='rr_street',
            field=models.CharField(max_length=200),
        ),
    ]
