# Generated by Django 3.1.1 on 2020-12-30 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0025_auto_20201230_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgenerate',
            name='pg_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 23, 43, 13, 193175)),
        ),
        migrations.AlterField(
            model_name='paymentpaid',
            name='pp_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 23, 43, 13, 193175)),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 23, 43, 13, 191151)),
        ),
        migrations.AlterField(
            model_name='roomallot',
            name='ra_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 23, 43, 13, 193175)),
        ),
        migrations.AlterField(
            model_name='roomquery',
            name='m_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 23, 43, 13, 193175)),
        ),
    ]
