# Generated by Django 3.1.1 on 2020-12-31 05:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0026_auto_20201230_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='house_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datawork.roomowner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomallot',
            name='house_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datawork.roomowner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentgenerate',
            name='pg_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 31, 11, 20, 3, 966494)),
        ),
        migrations.AlterField(
            model_name='paymentpaid',
            name='pp_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 31, 11, 20, 3, 966494)),
        ),
        migrations.AlterField(
            model_name='room',
            name='r_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 31, 11, 20, 3, 958271)),
        ),
        migrations.AlterField(
            model_name='roomallot',
            name='ra_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 31, 11, 20, 3, 962438)),
        ),
        migrations.AlterField(
            model_name='roomquery',
            name='m_doc',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 31, 11, 20, 3, 966494)),
        ),
    ]
